// This file is generated by tools/generate-di-registry.ts
import { registerDependencies } from '../mod.ts';
import { AppController } from './app.controller.ts';
import { SampleController } from './sample/sample.controller.ts';
import { SampleService } from './sample/sample.service.ts';
import { SharedService } from './shared/shared.service.ts';

registerDependencies(AppController, [SharedService]);
registerDependencies(SampleController, [SampleService, SharedService]);
